//register user
POST http://localhost:8080/api/customer/register
Content-Type: application/json

{
  "fullName": "Adam",
  "email": "adam@gmail.pl"
}

###

//search for rooms
GET http://localhost:8080/api/hotel/rooms/searchroom?city=Bialystok&startDay=2020-03-22&endDay=2020-03-26&priceFrom=150&priceTo=200
Accept: application/json

###

//book a room
POST http://localhost:8080/api/hotel/rooms/bookroom
Content-Type: application/json

{
  "roomId": 7,
  "userEmail": "adam@gmail.pl",
  "startDay": "2020-03-22",
  "endDay": "2020-03-28"
}

###

//check reservations
GET http://localhost:8080/api/hotel/reservations/check?customerEmail=adam@gmail.pl
Accept: application/json

###

//delete reservation
DELETE http://localhost:8080/api/hotel/reservations/cancel/12
Content-Type: application/json

###